### ISSUE TITLE
Move Repositories to this organization

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#1]
I see the following repos:

- [x] orbit https://github.com/haadcode/orbit
- [x] orbit-bot https://github.com/haadcode/orbit-bot
- [ ] ~~orbit-common https://github.com/haadcode/orbit-common~~
- [x] orbit-core https://github.com/haadcode/orbit-core
- [x] orbit-crypto https://github.com/haadcode/orbit-crypto
- [x] orbit-db https://github.com/haadcode/orbit-db
- [x] orbit-db-counterstore https://github.com/haadcode/orbit-db-counterstore
- [x] orbit-db-docstore https://github.com/shamb0t/orbit-db-docstore
- [x] orbit-db-eventstore https://github.com/haadcode/orbit-db-eventstore
- [x] orbit-db-feedstore https://github.com/haadcode/orbit-db-feedstore
- [x] orbit-db-kvstore https://github.com/haadcode/orbit-db-kvstore
- [x] orbit-db-pubsub https://github.com/haadcode/orbit-db-pubsub
- [x] orbit-db-store https://github.com/haadcode/orbit-db-store
- [ ] ~~orbit-irc (fork) https://github.com/haadcode/orbit-irc~~
- [ ] ~~orbit-server https://github.com/haadcode/orbit-server~~
- [x] orbit-textui https://github.com/haadcode/orbit-textui
- [ ] ~~planet-express https://github.com/haadcode/planet-express~~

Which should be moved here, @haadcode?

**Comment by haadcode** [comment]
I've striked-through the ones that don't need to be included. For the others, there's some re-organizing to be done before they can be moved. This will be one of my goals for this sprint.

**Comment by haadcode** [comment]
For `orbit-db-docstore`, we can ask @shamb0t if she'd be willing to transfer the original repo under this organization (https://github.com/shamb0t/orbit-db-docstore).

**Comment by shamb0t** [comment]
Just tried to transfer to orbitdb but I think I need permission to create a repository @haadcode @RichardLitt

**Comment by haadcode** [comment]
@shamb0t Thank you for jumping on it so quickly! I added you to the organization and you should be able to create repos now.

**Comment by shamb0t** [comment]
Easy peasy happy to help. All done!

**Comment by RichardLitt** [comment]
@shamb0t Made you an admin of that repo, again. You're the captain. I'll PR a README standardization - that OK with you?

**Comment by shamb0t** [comment]
@RichardLitt like the sound of captain 😎 of course no problem!

**Comment by RichardLitt** [comment]
(Also, off topic: @shamb0t wish you were in IRC! Would be good to say hi in person, as I am Montréal often).

**Comment by shamb0t** [comment]
That would be cool @RichardLitt but I live in Barcelona now! IRC may be easier :D

**Comment by RichardLitt** [comment]
@shamb0t Ah! Great. I'll check in when I am there this summer. :)

**Comment by RichardLitt** [comment]
@haadcode these are all yours now. Assigning you, waiting for the arrival of these in the org.

**Comment by haadcode** [comment]
Started the work before the weekend. I've been mainly working on splitting the code base of haadcode/orbit (the main repo, which will work as a landing page in the future for this org) and added two new repos:
- https://github.com/orbitdb/orbit-web
- https://github.com/orbitdb/orbit-electron

Transferred (and updated docs):
- https://github.com/orbitdb/orbit-core
- https://github.com/orbitdb/orbit-textui

haadcode/orbit will be transferred completely tomorrow. Rest will follow later this week.

**Comment by RichardLitt** [comment]
@haadcode Can I help more?

**Comment by haadcode** [comment]
All repos have now been transferred to https://github.com/orbitdb. Let me know if there are any problems with access rights, etc.

Thank you everyone for their work on the repos while they were under my account and getting Orbit this far together. We're still just getting started :) Here's to a great future to orbitdb organization and all its projects! 🍾 

✌️

**Comment by RichardLitt** [comment]
Woot.
