### ISSUE TITLE
orbit.chat domain

### ISSUE THREAD

**Issue by ghost** [orbitdb/welcome#11]
I still have orbit.chat - let me know where to move it. I'll keep renewing it until then :)

**Comment by RichardLitt** [comment]
@haadcode Do we have a company host account? Gandi? Should we set one up?

**Comment by ghost** [comment]
Easiest for the PL->Haja transfer would be if you open a Gandi account, then the transfer is instantly, and you can then move it anywhere without having to coordinate with me

**Comment by haadcode** [comment]
@lgierth I have setup account on Gandi, will ping you in PM to handle the transfer. Thank you for keeping the domain (and being willing to transfer the custody)! ❤️

**Comment by aphelionz** [comment]
@haadcode @RichardLitt Can this be closed?

**Comment by RichardLitt** [comment]
I'm not sure if Lars has transferred it over yet. :)

**Comment by ghost** [comment]
It's not transferred yet! cc @eefahy

It's in a Gandi account, and @haadcode made a Gandi account too (intra-registrar ownership change is much simpler than inter-registrar). The account it's in hasn't been upgraded to Gandi v5 yet, which made the transfer confusing to me, and then I got distracted with other stuff.

**Comment by RichardLitt** [comment]
So... @lgierth Do you need something from us?

**Comment by eefahy** [comment]
@RichardLitt I'll take care of it. I need your gandi account handle to transfer to.

**Comment by haadcode** [comment]
@eefahy thanks! You can transfer it to my account "haad" on Gandi.

**Comment by eefahy** [comment]
Unfortunately the process of changing the domain in gandi has changed. I need the contact information for the new owner:
- type of contact (choice of individual, company, association, public body)
- Legal Name of the Org
- First Name
- Family Name
- Country
- Street and number
- City
- Phone
- Email

If you'd rather not forward me that info then I can give you the transfer auth key and you could initiate the transfer on your end. Let me know which you prefer.

**Comment by haadcode** [comment]
@eefahy thanks for looking into it! Sounds like sensitive information needs to be exchanged, so let's do that in private. Can you reach out to me at haadcode at orbitdb.org to coordinate?

**Comment by RichardLitt** [comment]
I believe this can be closed, now. :)
