### ISSUE TITLE
Orbit Weekly Call: Tuesday July 24th

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#12]
Drop your agenda items here for the **July 24th 1300 UTC** community call for Orbit. 

Call details:

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/301508631  
Or iPhone one-tap : US: +19294362866,,301508631# or +16699006833,,301508631#  
Or Telephone: Dial(for higher quality, dial a number based on your current location): US: +1 929 436 2866 or +1 669 900 6833 Meeting ID: 301 508 631   International numbers available: https://zoom.us/u/gDwXenew

Notes will be pasted here after the call.

To be pinged before the call, subscribe to this issue.

**Comment by haadcode** [comment]
Let's take notes here: https://hackmd.io/ES1sA5hnSQKvYKLmKYv8bA

Call in 30mins!

**Comment by RichardLitt** [comment]
# orbit-db community call

date: Tue 24th of July, 2018
notetaker: @coyotespike
moderator: @RichardLitt

## participants
- @RichardLitt
- @haadcode
- @thiagodelgado111
- @vvp
- @shamb0t
- @sirfumblestone
- @coyotespike

## agenda
- Video?
    - It's pretty uncomfortable to 
    - TODO: @RichardLitt will write down reasons not to video in an issue the community repo. Policy is now not to, by unanimous consent.
- Assign notetaker and moderator
    - In the future let's rotate notetaker and moderator
    - TODO: @richardlitt will propose rotation cycle
- Previously on OrbitDB:
    - Notes: https://hackmd.io/5ZNf0nHnQSqUErnFREgFZg
- logo
    - there's new iterations, in the Github issue (https://github.com/orbitdb/welcome/issues/9)
    - TODO: @RichardLitt will ping about color variations
    - TODO: Everyone else, weigh in on the placement of the planets
- access controller
    - @haadcode @shamb0t worked on the design
    - based on @thiagodelgado111's PR and work
    - looks promising and possibly get it to a final PR this
    - @coyotespike: access control per entry
        - https://github.com/orbitdb/orbit-db/issues/409
        - Haad: Yes, should be possible witht he access controller, as long as it has access to the lists of the per-task access lists. Whether it's orbitdb acl or contract acl, that can be done. 
        - @thiago: Just wanted to share a gist with a few ideas I had on how I’d like to create and setup a store: https://gist.github.com/thiagodelgado111/706529326d488c558442f9055bd67d31
        - @coyotespike: key structure - see shamb0t's proposal on her ipfs-log fork, this also includes a solid proposal for key and signature structure
- Next release
    - Still hasn't happened, lots of new PRs, hasn't gotten to it yet. Hard to find the time to go through all of that. Would appreciate help! Check the PRs (for example that @mistakia has been making) and provide your feedback.
    - Supporting go-ipfs again, but the latest version (4.16) breaks all the tests, with some connection or race condition. The tests pass 50% of the time, which is not fun. (https://github.com/orbitdb/orbit-db/pull/417)
    - Perhaps just make a release and support up to 4.15 instead? We'll see. Haad will look into it this week, or ask the ipfs-devs what happened. 
- "Security bug"
    - Wasn't actually a bug, but it was a good fix. So, pulled in. \o/
- Replication perf in ipfs-log
    - Nothing to report
- Linting (standard vs airbnb's style)
    - @Haadcode will check this week.
    - @thiago has something about this on ipfs-log
        - https://github.com/orbitdb/ipfs-log/pull/130
        - https://github.com/orbitdb/orbit-db/issues/338
- Move repos from @haadcode to @orbitdb
    - Probably next week.
- OrbitDB or orbit-db?
    - @haadcode: OrbitDB
- Origin protocol is working on top of orbitdb, coolly?
    - @haadcode is talking to them, they're doing something similar to the access control. They're also doing encrypto for all messages, which adds another layer... 
    - We've been postponing crypto as long as possible, because it will raise expectations (I don't feel we're really ready for that yet)
    - No urgent need at the moment
    - Colony is more or less public, so it's not really a priority... yet. Topic comes up, but hasn't been started yet.
    - When will ipfs add sec?
        - Encrypted on the transport layer, but you can find some information out (who you're connected to and so on)
        - AFAIK not working on it right now, but sooner or later will be worked on.
