### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by haadcode** [orbitdb/welcome#14]
We should create a contribution guidelines for the OrbitDB projects.

In the past, we only had one or a handful of contributors and keeping code, docs and "git workflow" consistent wasn't much of an issue. As the community is growing, it'd be good to codify the guidelines, to make it easier to a) know how a contribution should look like and b) for maintainers to point to the guidelines to keep consistency.

The guideline should include instructions for at least:
- Code style
- Commit messages
- PR (eg. squashing)
- etc.

**Comment by RichardLitt** [comment]
@sirfumblestone I think you're working on this at the moment, right?

**Comment by sirfumblestone** [comment]
Yes I did. I went through the contribution document originally made by PL. However it needs updated OrbitDB contact addresses and the PR guidelines @haadcode mentioned. And for that I think e.g. you @RichardLitt might have better insight than me :)

**Comment by RichardLitt** [comment]
We have one, at the moment. Closing this. :) Thanks all!
