### ISSUE TITLE
Chat about orbit-db and CRDTs

### ISSUE THREAD

**Issue by haadcode** [orbitdb/welcome#2]
Me and @diasdavid were discussing on IRC that it would be good to sync with @pgte on orbit-db and specifically about CRDTs. We decided Thursday the 23rd (this week) would be a good day to do that.

@pgte when would be a good time for you on Thursday? Best for me would be in the morning, 9 UTC to 12 UTC, but I can also do 15 UTC. I think we should timebox this for an hour. Let me know your availability.

Everyone's welcome to join us and participate, or to just listen in! We'll post a zoom link before the chat.

**Comment by pgte** [comment]
Thursday, any time from 9 to 12 UTC is good for me. Let's say 10 to 11am UTC?

**Comment by haadcode** [comment]
10 to 11am UTC it is 👍 Looking forward to it!

**Comment by victorb** [comment]
I'll participate as a listener, sounds interesting :)

**Comment by haadcode** [comment]
Zoom link for the call: https://zoom.us/j/365100598

**Comment by haadcode** [comment]
Call was had, thoughts exchanged and next steps identified. Closing this issue, but feel free to re-open it or post notes here.

**Comment by daviddias** [comment]
Thank you all :)

@haadcode could you please update https://github.com/ipfs/research-CRDT with all the papers you have about the topic?
