### ISSUE TITLE
Repository templates

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#22]
I'd be happy to set up a repository template to make it easier to clone new repositories. Looking at https://github.com/orbitdb/orbit-db-identity-provider, there's some work that I could see that would immediately be useful; and rather than having me PR repos after they're made, or all of the orbitdb maintainers needing to remember what to do when creating them, I think a template might help out. 

Another option would be a 'Set up this repository' bot. That might work, too, and I know how I'd make it fairly quickly.

What do you think?

**Comment by shamb0t** [comment]
I think a template could be useful :+1:

**Comment by RichardLitt** [comment]
Alright! I've started work on one, here: https://github.com/orbitdb/repo-template. There are a few things that could be fixed, but in general, this should work pretty well to get going easier. 

Let me know what you think!
