### ISSUE TITLE
Community Calendar

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#32]
I'm attempting to set up a community calendar for us all to use, specifically for conferences, community calls, and other date-based events. I believe I might have gotten it with this:

https://calendar.google.com/calendar?cid=b3JiaXRkYi5vcmdfb2xrcWlyanFvazZwdGJuNnAxcGVrdmQyZ29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

However, you may need Google to sign in, which isn't ideal. Does this work for you? 

And has anyone heard of a good Google alternative for calendars? 

Eventually, I want to link to this from the README of this repository.

**Comment by haadcode** [comment]
Works for me.

**Comment by abh1manyu** [comment]
Works for me as well!
