### ISSUE TITLE
OrbitDB Community Call: Tuesday October 30

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#34]
### [Click here for the agenda and notes.](https://hackmd.io/6M1hUzrtTR2q_E3S0BagPw#)

This will be the next Orbit community call, on October 2nd at 1300UTC! Drop your agenda items here or in the notes.

Add this event to your calendar using [this link](https://calendar.google.com/event?action=TEMPLATE&tmeid=Xzg0cmowZTloNjRwMzZiOW42ZDBqMGI5azhrc2tjYjlwOG9zM2FiYTM4a3I0OGVhMTc0cGo2ZGhtOG9fMjAxODEwMDJUMTMwMDAwWiBvcmJpdGRiLm9yZ19vbGtxaXJqcW9rNnB0Ym42cDFwZWt2ZDJnb0Bn&tmsrc=orbitdb.org_olkqirjqok6ptbn6p1pekvd2go%40group.calendar.google.com&scp=ALL). 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/784309963

Or iPhone one-tap :
    US: +19294362866,,784309963#  or +16699006833,,784309963# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 929 436 2866  or +1 669 900 6833 
    Meeting ID: 784 309 963
    International numbers available: https://zoom.us/u/evzwWgnAi

====

Original message:

I was on a plane most of yesterday, and failed to remember to post the link last week for the call yesterday. I saw that some people tried to join the call anyway; I'm sorry about that!

What do you all think about having the community call next Tuesday at the regular time, 1300 UTC?

**Comment by haadcode** [comment]
I'd reckon doing the next one on regular schedule, is. no call this week and one next week.

**Comment by shamb0t** [comment]
I won't be able to join this week

**Comment by vvp** [comment]
I suggest we just keep the original schedule - so the next call would be Tue 30th at the regular time. Less rescheduling the better :slightly_smiling_face:

**Comment by RichardLitt** [comment]
Alright. Let's stick with next week, then! See you all in next Tuesday. :)

**Comment by RichardLitt** [comment]
Added a template for notes. Please update the agenda with what you'd like to talk about, ya'll. :)

**Comment by haadcode** [comment]
Note the time due to the daylight savings switch over the weekend! **1300 UTC**

**Comment by jarbacoa** [comment]
Would much appreciate a recording of this community call!

**Comment by RichardLitt** [comment]
@sharad-s  We do not record these calls, as we want people to feel comfortable joining in and talking without worrying about being recorded. We hope you can make it to be there with us - you don't need to have your mic or camera on. If you can't, we generally have good notes. :)

**Comment by shamb0t** [comment]
Notes posted [here](https://github.com/orbitdb/welcome/blob/93d7497fc111b8929677051a48eca85e4960945d/meeting-notes/2018/2018.10.30.md)
