### ISSUE TITLE
OrbitDB Community Call: Tuesday November 13

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#35]
### [Click here for the agenda and notes.](https://hackmd.io/Ky75XbELSAu6wb0BaKwOzA#)

This will be the next Orbit community call, on November 13 at 1300UTC! Drop your agenda items here or in the notes.

Add this event to your calendar using [this link](https://calendar.google.com/event?action=TEMPLATE&tmeid=Xzg0cmowZTloNjRwMzZiOW42ZDBqMGI5azhrc2tjYjlwOG9zM2FiYTM4a3I0OGVhMTc0cGo2ZGhtOG9fMjAxODEwMDJUMTMwMDAwWiBvcmJpdGRiLm9yZ19vbGtxaXJqcW9rNnB0Ym42cDFwZWt2ZDJnb0Bn&tmsrc=orbitdb.org_olkqirjqok6ptbn6p1pekvd2go%40group.calendar.google.com&scp=ALL). 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/784309963

Or iPhone one-tap :
    US: +19294362866,,784309963#  or +16699006833,,784309963# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 929 436 2866  or +1 669 900 6833 
    Meeting ID: 784 309 963
    International numbers available: https://zoom.us/u/evzwWgnAi

**Comment by shamb0t** [comment]
Notes [here](https://github.com/orbitdb/welcome/blob/master/meeting-notes/2018/2018.11.13.md)

**Comment by RichardLitt** [comment]
Thanks @shamb0t. Feel free to reference this issue number and close the issue out when adding the commit in the future. :)
