### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by bgbruno** [orbitdb/welcome#37]
Hello OrbitDB,

I read and watch #ipfs and I very like this working idea - I looking for "a private implementation" so data from my service will be available only on my servers across continents

Q I understand it right and #orbitdb just connect to already prepared #ipfs service <> or is in #orbitdb some security layer ?

thx

**Comment by aphelionz** [comment]
@bgbruno Access management is currently set at database creation time using the keypair provided by the underlying IPFS node. We are working on finer grained control over that as we speak.

In the meantime, if you're still in early phases of your product, one thing you can try is to set up a private IPFS cluster - one that doesn't automatically swarm and peer with other nodes that _aren't_ in the cluster. It's sort of a nuclear option at a lower layer than OrbitDB functionally operates at, but it would provide some control over where the data goes.

https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks

Just a suggestion, no strict guarantees :)

**Comment by bgbruno** [comment]
management is currently set ... using the keypair provided by the underlying IPFS node
Q thx @aphelionz pls what it means - that means data is swarmed on "public ipfs servers" but encrypted - and that is "based feature of ipfs"?

We are working on finer grained control over that as we speak.
Q great - means "more users on objects"?

one thing you can try is to set up a private IPFS cluster
yap I'm thinking about it

It's sort of a nuclear option
Q even if it is experimental for now - it's not how #ipfs is designed for?

**Comment by aphelionz** [comment]
> that means data is swarmed on "public ipfs servers" but encrypted - and that is "based feature of ipfs"?

It only means that the identity of your entries is the public key of the IPFS node writing them. It is not encrypted by default. If your node is public, it will swarm with othrer peers

> means "more users on objects"?

Short answer: Yes 

> it's not how #ipfs is designed for?

The private network is the nuclear option, it's an experimental feature of IPFS currently, as per the link I 
sent above. IPFS nodes are public default

**Comment by bgbruno** [comment]
that the identity of your entries ... It is not encrypted by default
OK thx

If your node is public, it will swarm with othrer peers
thx

more users on objects" ... Yes
great

The private network is the nuclear option ... nodes are public default
Q pls @aphelionz why you think it's "nuclear option" ?

it's an experimental feature
yap I know - personally I'm highly interested in

**Comment by aphelionz** [comment]
@bgbruno I call it a nuclear option because by creating a private IPFS network, you are effectively creating a sub-separate space that is not connected to the global IPFS network - so you have to weigh the pros and cons there.

**Comment by bgbruno** [comment]
nuclear ... because ... you are ... creating a sub-separate space ... not connected to the global IPFS network
ah I see how you mean that @aphelionz now - you know I want safely store data, so for sure to separate network, that is why I think about "private ipfs" - because if I understand it right when I use "global ipfs" I have to encrypt that data for security and decrypt only on client devices, and I cannot use them to calculation and indexing in my servers first
Q am I right?

**Comment by aphelionz** [comment]
@bgbruno 

> Q am I right?

That's exactly right. If you send something to an IPFS node in the global network, theoretically anybody can distover it.

**Comment by aphelionz** [comment]
Closing this issue for now - feel free to reopen or start a new thread if you have more questions :)
