### ISSUE TITLE
Move repositories from @haadcode to @orbitdb

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#4]
In a private discussion, we went over these repositories and wrote some brief notes on these repositories under @haadcode's namespace. There are a few repositories in @haadcode that might be better placed in @orbitdb, a few which would be better off deleted or archived, and some more which can just stay where they are.

@haadcode: Can you take a look at these, perform the appropriate action, and then check them off this list and close this issue, please?

### Move these to @orbitdb:

- [x] **[example-orbitdb-webpack](https://github.com/haadcode/example-orbitdb-webpack)** - An example how to use orbitdb through webpack.
- [x] **[ipfs-post](https://github.com/haadcode/ipfs-post)** - Datastructure for orbit-chat post. Rename, too.
- [ ] **[orbit-db-channelstore](https://github.com/haadcode/orbit-db-channelstore)** - Prototype of channelstore.
- [ ] **[orbit-db-http-server](https://github.com/haadcode/orbit-db-http-server)**

### Archive

Please archive these repositories. You can do this in the settings. Alternatively, delete them. We had marked them for deletion, but I don't think that's actually necessary; archiving them clearly shows they're not maintained or relevant, and keeps a track record in case you get subpoenaed by the Open Source police.

- [x] **[orbit-server](https://github.com/haadcode/orbit-server)**
- [x] **[ipfs-daemon](https://github.com/haadcode/ipfs-daemon)**

### Leave alone or undecided

We didn't decide what to do with these. Check these off when you've gone through and done the appropriate thing.

- [ ] **[go-ipfs-log](https://github.com/haadcode/go-ipfs-log)** - Prototype, long time ago, not finished. `@kex` has some go-ipfs stuff, too. Keep. Contact Kex.
- [x] **[immutabledb](https://github.com/haadcode/immutabledb)** - A way of doing a datastore, to use everything. Can store quite a bit of things. Instead of using IPFS, use anything else.
- [x] **[logplease](https://github.com/haadcode/logplease)**
- [x] **[planet-express](https://github.com/haadcode/planet-express)** - Twitter prototype. May have some screenshots. Kind of cool.
- [ ] **[pouchdb-adapter-orbitdb](https://github.com/haadcode/pouchdb-adapter-orbitdb)** - @haadcode will look into it.
- [x] **[proto2](https://github.com/haadcode/proto2)** - Visualization of orbitdb's dataflow and functions that may not work. Out of date.

And, in the IPFS Shipyard:

- [ ] **[ipfs-pubsub-peer-monitor](https://github.com/ipfs-shipyard/ipfs-pubsub-peer-monitor)** - Monitor peers joining and leaving an IPFS PubSub topic.

When you've done this, ping me please, as we should add the moved repositories to the directory in #3.

**Comment by RichardLitt** [comment]
While we're at it, can you take a look at **[example-orbitdb-todomvc](https://github.com/orbitdb/example-orbitdb-todomvc)** (Quote: "Someone is working on this. We should support that!") and **[orbitdb-orbit-crypto](https://github.com/orbitdb/orbitdb-orbit-crypto)** (Quote: "May not be used by anything. Needs to be checked by @haadcode.")? Thank you.

**Comment by RichardLitt** [comment]
@haadcode Can I help with any blockers for this?

**Comment by haadcode** [comment]
All the ones that are relevant have been transferred. orbit-db-channelstore and orbit-db-http-server can be left where they are, they're not in use anywhere and we don't plan to use them in OrbitDB.

I don't think we need to do anything with the repos of other users.

What else is needed here to finish/close the issue?

**Comment by RichardLitt** [comment]
Cool, thanks for the update. Nothing was needed but your go ahead. :)

**Comment by aphelionz** [comment]
@haadcode one last note on this - it appears somebody took the code from `orbit-db-http-server` and tried to add an HTTP server to the CLI. Did you see this PR?  

https://github.com/orbitdb/orbit-db-cli/pull/22

**Comment by haadcode** [comment]
Did not see that but replied, thanks for the ping!
