### ISSUE TITLE
calendar link broken

### ISSUE THREAD

**Issue by nuke-web3** [orbitdb/welcome#41]
In the readme - https://github.com/orbitdb/welcome/blob/master/calendar.google.com/calendar?cid=b3JiaXRkYi5vcmdfb2xrcWlyanFvazZwdGJuNnAxcGVrdmQyZ29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

this 404s.

Do you still hold open meetings?

**Comment by nuke-web3** [comment]
:man_facepalming:  #38  - might be too far off time wise to make this one - the link is still an issue though. and the calendar link in #38 expires recurring 12/10/18.
Looking forward to meeting you all!

**Comment by RichardLitt** [comment]
Thanks for pointing that out; works for me now. Let me know if it is still broken!

Think I may have a fix for the recurring link. Will work on it.

**Comment by RichardLitt** [comment]
I believe the recurring issue should also be fixed now. Zoom's scheduling feature has some bugs.
