### ISSUE TITLE
OrbitDB Community Call: January 8th!

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#42]
### [Click here for the agenda and notes.](https://hackmd.io/E1EiYggYTDaU5MQH0t4Bgw#)

This will be the next Orbit community call, on January 8th at 1400UTC! Drop your agenda items here or in the notes. **Note that this is an hour later than the last call.**

Add this event to your calendar using [this link](https://calendar.google.com/event?action=TEMPLATE&tmeid=Xzg0cmowZTloNjRwMzZiOW42ZDBqMGI5azhrc2tjYjlwOG9zM2FiYTM4a3I0OGVhMTc0cGo2ZGhtOG9fMjAxODEwMDJUMTMwMDAwWiBvcmJpdGRiLm9yZ19vbGtxaXJqcW9rNnB0Ym42cDFwZWt2ZDJnb0Bn&tmsrc=orbitdb.org_olkqirjqok6ptbn6p1pekvd2go%40group.calendar.google.com&scp=ALL). 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/784309963

Or iPhone one-tap :
    US: +19294362866,,784309963#  or +16699006833,,784309963# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 929 436 2866  or +1 669 900 6833 
    Meeting ID: 784 309 963
    International numbers available: https://zoom.us/u/evzwWgnAi

### Original Issue Comment (pre-edit)

Hey everyone! The next call falls on Christmas, and the week after that falls on New Years. We have a few options - we could meet before Christmas - say, on the 20th - or during the week between Christmas and New Years. What do you all think?

**Comment by haadcode** [comment]
I feel there's a good chance very few will be present on 25th or 1st (I personally won't make it). I'd propose we skip the next one and get back to regular programming on Jan 8th.

**Comment by RichardLitt** [comment]
Well, we wouldn't be able to have it on a Tuesday at all, yes. We could move to a Thursday or Friday. But I think that the 8th makes the most sense, too.

**Comment by aphelionz** [comment]
I'm happy to do it on the 8th.

**Comment by RichardLitt** [comment]
Let's do it on the 8th, then. I'll edit the first post to include the information.

**Comment by haadcode** [comment]
Notes https://github.com/orbitdb/welcome/blob/master/meeting-notes/2019/2019.01.08.md
