### ISSUE TITLE
Remove dates from Licenses

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#46]
The [Node Board](https://github.com/nodejs/TSC/issues/195#issuecomment-374443984) just pointed out that dates do not have any legal meaning in the License files. We can get rid of a non-negligible bit of admin by just removing them in the files, and in the Readme license section. What do you think?

**Comment by RichardLitt** [comment]
I'm following up with my legal to make sure.

**Comment by RichardLitt** [comment]
Hmm. Talked to my lawyer. Going to adopt this policy, as it seems best:

- Don't remove dates already in notices.
- Don't bother adding dates in new notices.
- Don't bother updating years in notices.

I'll add this to the global contribute, as it may come up in other repos.

**Comment by aphelionz** [comment]
> Don't bother updating years in notices.

This is interesting! I'm not questioning it but what's the rationale? Are the dates from the year carried forward automatically?

**Comment by RichardLitt** [comment]
Basically, the license doesn't need it, as far as I can tell. The license lasts for what, 75 years? And any updates made to the code probably restart the clock given the license, anyway.
