### ISSUE TITLE
OrbitDB Community Call: February 5th

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#48]
### [Click here for the agenda and notes.](https://hackmd.io/nCp-hk8KTfOlHQRabeGgjg#)

This will be the next Orbit community call, on February 5th at 1400UTC! Drop your agenda items here or in the notes. **Note that this is an hour later than the last call.**

Add this event to your calendar using [this link](https://calendar.google.com/event?action=TEMPLATE&tmeid=Xzg0cmowZTloNjRwMzZiOW42ZDBqMGI5azhrc2tjYjlwOG9zM2FiYTM4a3I0OGVhMTc0cGo2ZGhtOG9fMjAxODEwMDJUMTMwMDAwWiBvcmJpdGRiLm9yZ19vbGtxaXJqcW9rNnB0Ym42cDFwZWt2ZDJnb0Bn&tmsrc=orbitdb.org_olkqirjqok6ptbn6p1pekvd2go%40group.calendar.google.com&scp=ALL). 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/784309963

Or iPhone one-tap :
    US: +19294362866,,784309963#  or +16699006833,,784309963# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 929 436 2866  or +1 669 900 6833 
    Meeting ID: 784 309 963
    International numbers available: https://zoom.us/u/evzwWgnAi

**Comment by hacker-DOM** [comment]
I'll be joining today. We're trying to build a decentralized education system. It's called Solvio (https://solvio.discourse.group). I'd love to discuss the current state of the art when it comes to public databases secured by cryptography, and whether it's at a level where it can be used in production for a consumer app. Looking forward to it!

**Comment by RichardLitt** [comment]
Closed in eafcd803e0dacdfa9456f932855ba3cc5012f112. Thanks all.
