### ISSUE TITLE
OrbitDB Community Call: February 19th

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#49]
### [Click here for the agenda and notes.](https://hackmd.io/eTF3S13FTHacA9qyIWtpYw#)

This will be the next Orbit community call, on February 19th at 1400UTC! Drop your agenda items here or in the notes. **Note that this is an hour later than the last call.**

Add this event to your calendar using [this link](https://calendar.google.com/event?action=TEMPLATE&tmeid=Xzg0cmowZTloNjRwMzZiOW42ZDBqMGI5azhrc2tjYjlwOG9zM2FiYTM4a3I0OGVhMTc0cGo2ZGhtOG9fMjAxODEwMDJUMTMwMDAwWiBvcmJpdGRiLm9yZ19vbGtxaXJqcW9rNnB0Ym42cDFwZWt2ZDJnb0Bn&tmsrc=orbitdb.org_olkqirjqok6ptbn6p1pekvd2go%40group.calendar.google.com&scp=ALL). 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/784309963

Or iPhone one-tap :
    US: +19294362866,,784309963#  or +16699006833,,784309963# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 929 436 2866  or +1 669 900 6833 
    Meeting ID: 784 309 963
    International numbers available: https://zoom.us/u/evzwWgnAi

**Comment by haadcode** [comment]
Notes here https://github.com/orbitdb/welcome/pull/50 and copy-pasted here:

---

# OrbitDB Community Call February 19th

- **Moderator:** @RichardLitt
- **Notetaker:** @haadcode
- **Attendees:**
- @RichardLitt
- @Shamb0t
- @Haadcode
- @Schwartz10

## Moderator checklist

- [ ] Ensure that the moderator last week is the notetaker, or that someone else has volunteered
- [ ] Call for additional agenda items

## Agenda

- Update on next release:
    - PR#495 is the main PR, almost ready but want to test it more thoroughly
    - One known issue (through Orbit Chat) to fix
    - Need up date rest of the documentations
    - ETA this week, we hope
    - Big release, new access controller, identity system, improved log etc.
- @Schwartz10
    - evaluating OrbitDB, wanted to get an idea what to expect in terms of "production readiness"
    - generally production ready, but alpha-level software so APIs may break in the future, hasn't been security audited so heads-up
- @Abhi
    - Working on SmartX, using OrbitDB, really easy to get an app started and built with it
    - many questions, will follow up on Gitter

## Q&A, Help Wanted, Demos

- none

**Comment by RichardLitt** [comment]
Thanks, @haadcode.
