### ISSUE TITLE
OrbitDB Community Call: April 2nd

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#54]
### [Click here for the agenda and notes.](https://hackmd.io/tX88txFDSbCXAKsIZWW5FA#)

This will be the next Orbit community call, on April 2nd at 1400UTC! Drop your agenda items here or in the notes. **Note that this is an hour later than the last call.**

Add this event to your calendar using [this link](https://calendar.google.com/event?action=TEMPLATE&tmeid=Xzg0cmowZTloNjRwMzZiOW42ZDBqMGI5azhrc2tjYjlwOG9zM2FiYTM4a3I0OGVhMTc0cGo2ZGhtOG9fMjAxODEwMDJUMTMwMDAwWiBvcmJpdGRiLm9yZ19vbGtxaXJqcW9rNnB0Ym42cDFwZWt2ZDJnb0Bn&tmsrc=orbitdb.org_olkqirjqok6ptbn6p1pekvd2go%40group.calendar.google.com&scp=ALL). 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/784309963

Or iPhone one-tap :
    US: +19294362866,,784309963#  or +16699006833,,784309963# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 929 436 2866  or +1 669 900 6833 
    Meeting ID: 784 309 963
    International numbers available: https://zoom.us/u/evzwWgnAi

**Comment by haadcode** [comment]
Notes:

# OrbitDB Community Call April 2nd

- **Moderator:** @RichardLitt
- **Notetaker:** @haadcode
- **Attendees:**
    - @aphelionz
    - @vvp
    - @shamb0t
    - @haadcode
    - @RichardLitt
    - @JaniAnttonen
    - @oed
    - Abhi
    - @HaydenYoung

## Agenda
_General discussions, decisions, etc._

- OrbitDB 0.20.0 release, release candidate (@haadcode, 5mins)
    - 0.20.0 RC out! `npm install --save orbit-db@rc1`
    - There's release notes PR to read more about it: https://www.npmjs.com/package/orbit-db/v/0.20.0-rc.1
    - New access controllers, should be backwards compatible
    - All feedback and comments welcomed!
    - Changelog: https://github.com/orbitdb/orbit-db/blob/296adda6c7a6f10113a3a30e5fc3cd0420e73726/CHANGELOG.md
- Update on Orbit Chat (@JaniAnttonen)
    - @latenssi has been working ipfs-log (remove in-memory caching) 
    - Working to make loading of old messages work better
    - 3 PRs open
    - tried out with orbit-db RC1, working to fix it (doesn't work yet, some error with the identity-provider)
- @phillmac and @hayden have been diligently working on a orbit-db REST API
    - should we test with the RC or wait for the official release?
        - should test it, the orbit-db API has changed (how to create an instance) so hopefully that works
    - almost there, awesome to see it happen
- Stickers! They're here!
    - Send richardlitt@orbitdb.org your address and how many you want, and he'll send them to you. 
- @oed on the approach to test the new release:
    - can I migrate a database without migrating the data of the database
        - yes, but you need to create a new key from the old keys (see identity-provider docs)
        - old identities can't append anymore (?), but the data will be there
        - https://github.com/orbitdb/orbit-db-identity-provider#create-identity-using-existing-keys

**Comment by RichardLitt** [comment]
Thanks all!
