### ISSUE TITLE
Question about replication model

### ISSUE THREAD

**Issue by keepsimple1** [orbitdb/welcome#59]
Hi, 

This is a question, not a bug or real issue. If this is not the best place to ask questions, please let me know. 

I wanted to understand the replication model used / supported by orbit-db.  e.g. 
- Can I set a replication factor?  (e.g. have exact 2 copies for every data?) .   
- Does orbit-db allow running only on a single node (maybe only for a short time when other nodes are down) and still allow writes?

**Comment by aphelionz** [comment]
Hi @keepsimple1. Thanks for opening the issue.

1. Right now any peer that connects to any database address will replicate the data, so it doesnt necessarily happen automatically based on creation, i.e. it doesn't automatically propogate outward to the network. You can control this by setting up a "pinning service" of your own. Several apps do this and you can see an example here. https://github.com/3box/3box-pinning-node

2. You can run orbitdb on a single node for as long as you want - in fact you can _never_ connect to any other peers and still have a working "offline" application

We have a full Field Manual here, which includes a tutorial: https://github.com/orbitdb/field-manual. Feel free to ask any other questions you have in that repo!
