### ISSUE TITLE
OrbitDB Community Call: June 11th, 2019

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#62]
### [Click here for the agenda and notes.](https://hackmd.io/Ze1aOGZrR2WCWENvPNSO_A)

This will be the next Orbit community call, on June 11th at 1400UTC! Drop your agenda items here or in the notes.

Add this event to your calendar using [this link](https://calendar.google.com/event?action=TEMPLATE&tmeid=Xzg0cmowZTloNjRwMzZiOW42ZDBqMGI5azhrc2tjYjlwOG9zM2FiYTM4a3I0OGVhMTc0cGo2ZGhtOG9fMjAxODEwMDJUMTMwMDAwWiBvcmJpdGRiLm9yZ19vbGtxaXJqcW9rNnB0Ym42cDFwZWt2ZDJnb0Bn&tmsrc=orbitdb.org_olkqirjqok6ptbn6p1pekvd2go%40group.calendar.google.com&scp=ALL). 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/784309963

Or iPhone one-tap :
    US: +19294362866,,784309963#  or +16699006833,,784309963# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 929 436 2866  or +1 669 900 6833 
    Meeting ID: 784 309 963
    International numbers available: https://zoom.us/u/evzwWgnAi

**Comment by Jon-Biz** [comment]
Is this still an active call? Doesn't seem to be anyone around right now.

**Comment by shamb0t** [comment]
@Jon-Biz sincere apologies! We weren't able to make it today as we're preparing for the Berlin [meetup](https://github.com/orbitdb/welcome/issues/63). Next call will be in 2 weeks on June 25th.

**Comment by RichardLitt** [comment]
Sorry Jon! If you jump on the Gitter we'd be happy to talk about stuff async. I was organizing the meetup today and wasn't able to join as I thought I would be able to.
