### ISSUE TITLE
Clarify who orbitdb/maintainers are

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#7]
Right now, @orbitdb/maintainers goes to @VictorBjelkholm and @diasdavid and @dignifiedquire, which is great (hi guys 👋), but I don't think they are actually maintaining this anymore. 

Do you guys want to stay as the maintainers, or are you OK if we remove you from that team?

**Comment by dignifiedquire** [comment]
Hey Richard :)

Fine to remove me, I am not maintaining things currently here

**Comment by daviddias** [comment]
Go ahead 👍

**Comment by RichardLitt** [comment]
Done. @VictorBjelkholm, any thoughts? :)

**Comment by victorb** [comment]
I'm fine with being removed as well :)

**Comment by RichardLitt** [comment]
Thanks all. :)
