### ISSUE TITLE
OrbitDB Logo

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/welcome#9]
I had my friend Pablo whip up some logo designs for us. These are from the second iteration; what do you think? Any and all comments are welcome. 

[Haja_Orbit_v2.pdf](https://github.com/orbitdb/welcome/files/2180831/Haja_Orbit_v2.pdf)

There are three versions here.

Personally, I'm a fan of the middle one the most, I think.

**Comment by vvp** [comment]
They all look great! Comments about different versions :
- First one - Text in one line, which I personally love but it makes hexagonal logos a bit too compact.
- Second one - "orbit" and "db" in separate lines makes hexagonal logos more readable vs first one. I do wonder why "db" is in smaller font (are we more orbit than db? :slightly_smiling_face: )
- Third one - "orbit" and "db" in separate lines, but in different font which bothers me a bit personally. OTOH I think I like the slightly different "orbit" font here more than in first and second ones.

**Comment by RichardLitt** [comment]
Thanks @vvp :) 

I want to wrap this up; I am planning to close this to comments and to pick based on this feedback and other's thoughts next Tuesday during the weekly call. I think that makes the most sense. I've given Pablo feedback, and we may have more iterations by then, too, which we can talk over.

**Comment by haadcode** [comment]
*(for context, I've given feedback on this earlier, but adding my comments here for public discussion)*

I really like the overall design! 👍❤️

- As per previous discussions offline, I'd still want to see color variations. While I like the orange scheme, I feel from communication perspective, we should try out a red/pink-ish/magenta-ish color: as we're on the "interplanetary" theme, and have talked about getting to Mars some day, perhaps "red planet" could work?
- Regarding the font, I feel it's a bit too round and again, given our "spacey" theme, I feel something more "techy/sci-fi" could work well.
- Regarding the layout: in the first iteration, there was a clear space between "O" and "r" which made the planet(s) stand out really nicely. In this iteration the "r" is overlapping the planet a bit and it feels a bit cluttered and/or off. I also think that the scale of the red and black planets in the second option in this iteration are better than in the first option, but generally feel the first option (where orbitdb are together) works better. The second option where they are separate feels off (perhaps the "db" is the second option is too big?)

**Comment by RichardLitt** [comment]
Got an iteration back! Still need some color variations, though. 

<img width="524" alt="screen shot 2018-07-24 at 08 38 33" src="https://user-images.githubusercontent.com/910753/43138473-fa9070f0-8f1c-11e8-9170-f271e8f657ed.png">

**Comment by thiagodelgado111** [comment]
I like option 1 :)

**Comment by coyotespike** [comment]
I would rank these designs, starting with my favorite: 3, 1, original, 2. You could also mix and match, maybe the large planet and text from 2, and the smaller shapes from 3.

**Comment by RichardLitt** [comment]
We have some new colors! What do you all think? 

[Haja_Orbit_v3_2.pdf](https://github.com/orbitdb/welcome/files/2249349/Haja_Orbit_v3_2.pdf)

**Comment by RichardLitt** [comment]
In the interest of moving this forward: I'm going to finalize the logo end of day tomorrow. Votes and thoughts here will factor into that, and I'll try to be impartial. At the moment, I'm in favor of #5 from the new ones. :)

**Comment by sirfumblestone** [comment]
My vote goes to the deep red number 5 🤘

**Comment by thiagodelgado111** [comment]
From the new batch, I like 4 and 5

**Comment by RichardLitt** [comment]
Alright! Friday came and passed; I had some more feedback off-issue, and now we have another round of iterations. :) 

[Haja_Orbit_v3_2_red.pdf](https://github.com/orbitdb/welcome/files/2271949/Haja_Orbit_v3_2_red.pdf)

See the final page for color and `r` differences. What do ya'll think?

**Comment by IbbyBenali** [comment]
@RichardLitt I like them :) I was actually just looking for some logos of OrbitDB, glad to see that there will also be logo's with the text "orbitdb". I have one suggestion, maybe also create black and white options in addition as specifically these may sometimes be needed (e.g. greyed out logo displays on websites, or perhaps black and white prints).

**Comment by pabslabs** [comment]
Hey! Here's the guidelines document of the logo. I added recommendations of use and some colour and position variations. I included a small description and the CC-BY-SA License too. 
This PDF can be open in Adobe Illustrator to edit it the vector logo and variations.
Let me know what you think.
[orbit_db_guidelines.pdf](https://github.com/orbitdb/welcome/files/2384973/orbit_db_guidelines.pdf)

**Comment by haadcode** [comment]
Thank you @pabslabs for jumping in and posting the new versions!

I think the guidelines and the logo are great and the fact that this gets open sourced is ❤️

I like the (main) red color, but seeing them now in finalized form all at once, I personally would like the first color variation (first from the top on the last page) as the default and the pink one (second variation) is really cool too :) Any opinions?

I was wondering if we should make the "db" on the textured backgrounds (eg. hexagons) white as it was in the [earlier orange version](https://github.com/orbitdb/welcome/files/2271949/Haja_Orbit_v3_2_red.pdf). No strong opinion on that, @pabslabs what do you think?

Note also that there's a slight mismatch between the font sizes and positioning between color variation 1 and 2, would be good to adjust that so have all of them at same proportions.

**Comment by RichardLitt** [comment]
> I like the (main) red color, but seeing them now in finalized form all at once, I personally would like the first color variation (first from the top on the last page) as the default and the pink one (second variation) is really cool too :) Any opinions?

I frankly [can't see red shades](https://en.wikipedia.org/wiki/Color_blindness) all that well. I'm going to recuse myself from color considerations. 

I prefer the white `db`.

**Comment by pabslabs** [comment]
Hey, I see what you mean, the two colour options are very similar, the main logo is a bit more orange/red while the first variation is more red/magenta. I personally prefer the more orange/red version. I think is closer to a real planet's colour. 

For the back textures, it's all about the contrast on each situation, when the background gets darker is time to use the white version. I made some more examples.

![screen shot 2018-09-21 at 12 20 42 pm](https://user-images.githubusercontent.com/32751829/45893488-6790f800-bd99-11e8-9445-957f7ec94fc0.png)

**Comment by pabslabs** [comment]
Hello!
Here's a new version of the guidelines document. I changed the main version of the logo for the more red, less orange option. Let me know what you think.
Thanks!
Pablo
[orbit_db_guidelines02.pdf](https://github.com/orbitdb/welcome/files/2429749/orbit_db_guidelines02.pdf)

**Comment by haadcode** [comment]
@pabslabs apologies for the delay in answering! @RichardLitt pinged me on this and had completely missed your previous message with the latest updates to the logo.

I'm happy with it now and the latest version addresses the issues raised earlier. Thank you @pabslabs for creating this and sharing with the community! ❤️🎉 

I'd be glad if we started using it throughout the community (eg. on Github pages, print some stickers, etc.).

**Comment by RichardLitt** [comment]
Awesome. :) @pabslabs Can you upload some different formats of the final version, so it's not just in a PDF?

**Comment by pabslabs** [comment]
Hello @RichardLitt and @haadcode !
Thanks for the message, I am glad you like it! I'm going to produce more formats of the logo (JPG, PNG, EPS, AI...) and upload them here. Is it OK if I upload a zip with everything?
Cheers!

**Comment by RichardLitt** [comment]
A zip works. If you want to learn how to use GitHub, you could upload it into a repo too. :)

**Comment by pabslabs** [comment]
OK! I am going to try to create the repository and upload the files there.
I'll let you know how it goes :)

**Comment by pabslabs** [comment]
I think I did it... but I am not sure.
I created a repository and put some files in it. Does this work? Should I add you as contributors too?
https://github.com/pabslabs/OrbitDB-logotype

**Comment by RichardLitt** [comment]
That's pretty much perfect. :) All good!

**Comment by RichardLitt** [comment]
We... have a logo?

**Comment by haadcode** [comment]
We have a logo and the assets are here https://github.com/orbitdb/logo.

Thank you @pabslabs and everyone for input! 🎉

**Comment by RichardLitt** [comment]
Edit: Wrong issue.

Thanks, @haadcode. :) And thank you, Pablo!

**Comment by pabslabs** [comment]
Thank you! Always a pleasure to be part of great teams and projects like this one!
Let me know if you need to design more stuff! 😄
